### ISSUE TITLE
Save the .csv file

### ISSUE THREAD

**Issue by cdhekne** [kgary/REACHv1#25]
Save it to the file system. 

(Nice to have) call the Share to email as an attachment to Gmail

**Comment by mpatward** [comment]
EVENTS are tracked in EVENT_TRACKER table and are converted to a CSV file with Date and Time of the event, event type and EVENT_LOCATION details.

**Comment by cdhekne** [comment]
REACH_Data.csv file is saved in the Android File system. Moved the code to save the file in Preferences Menu
