### ISSUE TITLE
Admin - STIC preferences

### ISSUE THREAD

**Issue by msmtms** [kgary/REACHv1#71]
The bug seems to be that when 6 updates have been made, to any week, all are permanent. No other change can be made.

**Comment by msmtms** [comment]
It seems to be that when there is no update to be made that it locks, such as if "both" is selected, and you select "both" again for the same week, or if cancel is selected, at that point it doesn't allow any changes for anything.

**Comment by cdhekne** [comment]
Derek, I doubled-tripled checked the code for this. I have written an On-change listener for this, so only when there's a change in the selection, it will be reflected in the database. The thing which you were suggesting about it not allowing to update after 6 times, I didn't have any issue with that. I was debugging it line-by-line for half hour just to check whether it does this. 

I think the 1st two lines of this comment explain why you were having this issue.
