### ISSUE TITLE
Invalid day message on activities after first provisioning

### ISSUE THREAD

**Issue by kgary** [kgary/REACHv1#82]
In testing the latest version of the app, I set the start date of the protocol to the present day (3/11) and then I run the app. With the Daily Diary activity I get a toast message "Invalid day please change start date" although it does allow me to do the activity. I also get the message when selecting the Relaxation activity, but only when I tap "Back" and return to the landing screen.

**Comment by msmtms** [comment]
Fixed to where today is day 1 instead of day 0
