### ISSUE TITLE
STOP/Daily Diary - Keyboard

### ISSUE THREAD

**Issue by msmtms** [kgary/REACHv1#92]
Button to make keyboard go away

**Comment by msmtms** [comment]
There are now three ways to close the keyboard when responding in daily diary and stop. If anybody else complains about this, they're getting slapped.

**Comment by kgary** [comment]
![iw0r7](https://cloud.githubusercontent.com/assets/1686725/6658715/885ca346-cb2f-11e4-8050-bf0211504c06.jpg)
